### ISSUE TITLE
better handle of not null

### ISSUE THREAD

**Issue by sibelius** [gajus/database-types#7]
current output:

`updatedAt: string | null`

it should be `updatedAt?: string`

**Comment by gajus** [comment]
Whats wrong with `string | null` for a nullable type?

**Comment by sibelius** [comment]
I think it is the same, I little bit more verbose

**Comment by gajus** [comment]
It is not the same.

`?:` allows omission of the property.

`| null` allows value to be null, but does not allow omission of the property.

The difference is important, because in one case you need to do check such as `movie.updatedAt && movie.updatedAt === 'something'` and in the `| null` case just `movie.updatedAt === 'something'` is enough.

**Comment by sibelius** [comment]
what about 

`updatedAt: ?string`

?

**Comment by gajus** [comment]
Looks like thats a shortcut for `| null`.

I have not seen it in the docs, but it is documented here.

https://stackoverflow.com/a/37174244/368691
